In [1]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

In [5]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as `np`::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide addit

In [7]:
np.arange.__doc__

'arange([start,] stop[, step,], dtype=None, *, like=None)\n\n    Return evenly spaced values within a given interval.\n\n    ``arange`` can be called with a varying number of positional arguments:\n\n    * ``arange(stop)``: Values are generated within the half-open interval\n      ``[0, stop)`` (in other words, the interval including `start` but\n      excluding `stop`).\n    * ``arange(start, stop)``: Values are generated within the half-open\n      interval ``[start, stop)``.\n    * ``arange(start, stop, step)`` Values are generated within the half-open\n      interval ``[start, stop)``, with spacing between values given by\n      ``step``.\n\n    For integer arguments the function is roughly equivalent to the Python\n    built-in :py:class:`range`, but returns an ndarray rather than a ``range``\n    instance.\n\n    When using a non-integer step, such as 0.1, it is often better to use\n    `numpy.linspace`.\n\n    See the Warning sections below for more information.\n\n    Parameter

In [8]:
import time

In [9]:
time.time()

1680274025.0165665

In [10]:
start = time.time()

In [11]:
start

1680274097.936855

In [17]:
size = 10000000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result = [(x+y) for x, y in zip(l1,l2)]
print("Python list took: ", (time.time() - start) * 1000)

start = time.time()
result = a1 + a2
print("numpy took: ", (time.time() - start) * 1000)

Python list took:  774.4448184967041
numpy took:  87.0676040649414


In [18]:
import sys

In [19]:
sys.getsizeof(5)

28

In [20]:
sys.getsizeof(5555)

28

In [21]:
sys.getsizeof(555555)

28

In [22]:
sys.getsizeof("a")

50

In [23]:
sys.getsizeof("aaaaa")

54

In [26]:
l = range(1000)
print(sys.getsizeof(5))
print(sys.getsizeof(5) * len(l))

a = np.arange(1000)

print(a.itemsize)
print(a.itemsize * a.size)

28
28000
4
4000


In [27]:
a = [1,2,3,4]
b = [4,3,2,1]

In [28]:
ab = []

for i in range(0,len(a)):
    ab.append(a[i] * b[i])
ab

[4, 6, 6, 4]

In [29]:
a1 = np.array(a)
a2 = np.array(b)

In [30]:
a1 * a2

array([4, 6, 6, 4])

In [31]:
a1 / a2

array([0.25      , 0.66666667, 1.5       , 4.        ])

In [32]:
a1 + a2

array([5, 5, 5, 5])

In [33]:
a1 - a2

array([-3, -1,  1,  3])

## 1 Array

In [34]:
mylist = [1,2,3]
mylist

[1, 2, 3]

In [35]:
np.array(mylist)

array([1, 2, 3])

In [36]:
np.array([1,2,3])

array([1, 2, 3])

In [37]:
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [38]:
mylist2 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
mylist2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [39]:
myarray = np.array(mylist2)

In [40]:
myarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

##  2 shape & reshape

In [41]:
myarray.shape

(4, 3)

In [43]:
myarray.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
myarray.reshape(2,4) # don't forget that while reshaping the arrays, the number of elements containing arrays should be same

ValueError: cannot reshape array of size 12 into shape (2,4)

In [47]:
myarray.reshape(4,4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [51]:
myarray.reshape(12).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [52]:
myarray.reshape(12).reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [55]:
myarray.reshape(-1,4) # -1 means unknown

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
myarray.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
myarray.reshape(12).reshape(2,-1,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# 3 ndim

In [63]:
mylist = list(range(0,13))

In [64]:
print(mylist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [65]:
mylist # by clicking the box in the left of o/p we can open and close it

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [67]:
myarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
myarray.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
myarray = np.array(mylist,ndim = 4)

TypeError: array() got an unexpected keyword argument 'ndim'

In [71]:
myarray = np.array(mylist,ndmin = 4)
myarray

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

# 4 dtype & astype

In [72]:
myint = np.array([1,2,3])
myint

array([1, 2, 3])

In [73]:
myint.dtype

dtype('int32')

In [74]:
myfloat = np.array([1.,2.,3.,6,5])
myfloat

array([1., 2., 3., 6., 5.])

In [75]:
myfloat.dtype

dtype('float64')

In [76]:
mystring = np.array([1.,2.,3.,6,5,"s"])
mystring

array(['1.0', '2.0', '3.0', '6', '5', 's'], dtype='<U32')

In [77]:
mystring.dtype

dtype('<U32')

In [80]:
x = np.array([1,2],dtype = np.float32)
print(x)
print(x.dtype)

[1. 2.]
float32


In [81]:
newx = x.astype("i")
print(newx)
print(newx.dtype)

[1 2]
int32


In [82]:
arr = np.array([0,1,2])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[False  True  True]
bool
